import React from 'react';
import type { Listing } from './types';

// Fix: Add featured residential listings data
export const FEATURED_LISTINGS: Listing[] = [
  {
    id: 1,
    address: '123 Main St',
    city: 'Lawrenceville',
    state: 'Pennsylvania',
    zipCode: '15201',
    price: 350000,
    type: 'Residential',
    sqft: 1800,
    beds: 3,
    baths: 2,
    yearBuilt: 1955,
    propertyStyle: 'Colonial',
    condition: 'Good',
    features: ['Hardwood Floors', 'Updated Kitchen', 'Fireplace', 'Private Backyard'],
    appliances: ['Dishwasher', 'Refrigerator', 'Gas Stove'],
    heating: 'Gas',
    cooling: 'Central Air',
    flooring: ['Hardwood', 'Tile'],
    images: ['https://picsum.photos/seed/lawrenceville-colonial/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Charming 3-bedroom colonial in the heart of Lawrenceville with original hardwood floors, updated kitchen featuring granite counters and stainless appliances, cozy fireplace in the living room, and a private backyard perfect for entertaining. Walking distance to Butler Street restaurants and shops.'
  },
  {
    id: 2,
    address: '456 Butler St',
    city: 'Squirrel Hill',
    state: 'Pennsylvania',
    zipCode: '15217',
    price: 425000,
    type: 'Residential',
    sqft: 2400,
    beds: 4,
    baths: 3,
    yearBuilt: 1920,
    propertyStyle: 'Tudor',
    condition: 'Excellent',
    features: ['Original Details', 'Sunroom', 'Walk-in Closets', 'Garden'],
    appliances: ['Dishwasher', 'Refrigerator', 'Washer', 'Dryer'],
    heating: 'Radiant',
    cooling: 'Window Units',
    flooring: ['Hardwood', 'Carpet'],
    images: ['https://picsum.photos/seed/squirrel-hill-tudor/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Stunning Tudor home in desirable Squirrel Hill featuring original architectural details, spacious sunroom, updated kitchen with custom cabinetry, and beautiful gardens. Close to Carnegie Mellon University and Frick Park.'
  },
  {
    id: 3,
    address: '789 Penn Ave',
    city: 'Bloomfield',
    state: 'Pennsylvania',
    zipCode: '15224',
    price: 299000,
    type: 'Residential',
    sqft: 1500,
    beds: 3,
    baths: 1,
    yearBuilt: 1970,
    propertyStyle: 'Ranch',
    condition: 'Fair',
    features: ['One Level Living', 'Large Windows', 'Detached Garage'],
    appliances: ['Dishwasher'],
    heating: 'Electric',
    cooling: 'None',
    flooring: ['Carpet', 'Vinyl'],
    images: ['https://picsum.photos/seed/bloomfield-ranch/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Affordable ranch-style home in Bloomfield with one-level living, large windows for natural light, and detached garage. Great starter home or investment property in an up-and-coming neighborhood.'
  },
  {
    id: 4,
    address: '555 Walnut St',
    city: 'Shadyside',
    state: 'Pennsylvania',
    zipCode: '15232',
    price: 550000,
    type: 'Residential',
    sqft: 2800,
    beds: 4,
    baths: 4,
    yearBuilt: 2010,
    propertyStyle: 'Modern',
    condition: 'Excellent',
    features: ['Open Floor Plan', 'High Ceilings', 'Smart Home', 'Rooftop Deck'],
    appliances: ['Dishwasher', 'Refrigerator', 'Washer', 'Dryer', 'Wine Cooler'],
    heating: 'Heat Pump',
    cooling: 'Central Air',
    flooring: ['Hardwood', 'Tile', 'Concrete'],
    images: ['https://picsum.photos/seed/shadyside-modern/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Luxurious modern home in Shadyside with open floor plan, high ceilings, smart home technology, and rooftop deck with city views. Premium finishes throughout including gourmet kitchen and spa-like bathrooms.'
  },
  {
    id: 5,
    address: '321 Highland Ave',
    city: 'Mount Washington',
    state: 'Pennsylvania',
    zipCode: '15211',
    price: 675000,
    type: 'Residential',
    sqft: 3200,
    beds: 5,
    baths: 3,
    halfBaths: 1,
    yearBuilt: 1985,
    propertyStyle: 'Contemporary',
    condition: 'Excellent',
    features: ['City Views', 'Deck', 'Finished Basement', 'Two-Car Garage'],
    appliances: ['Dishwasher', 'Refrigerator', 'Washer', 'Dryer', 'Microwave'],
    heating: 'Gas',
    cooling: 'Central Air',
    flooring: ['Hardwood', 'Tile', 'Carpet'],
    images: ['https://picsum.photos/seed/mount-washington-contemporary/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Spectacular contemporary home on Mount Washington with breathtaking city skyline views from multiple levels. Features open concept living, finished basement, large deck, and attached two-car garage. Perfect for entertaining with panoramic downtown views.'
  },
  {
    id: 6,
    address: '789 Forbes Ave',
    city: 'Oakland',
    state: 'Pennsylvania',
    zipCode: '15213',
    price: 485000,
    type: 'Residential',
    sqft: 2100,
    beds: 3,
    baths: 2,
    yearBuilt: 1960,
    propertyStyle: 'Split Level',
    condition: 'Good',
    features: ['Near Universities', 'Large Lot', 'Updated Bathrooms', 'Hardwood Floors'],
    appliances: ['Dishwasher', 'Refrigerator', 'Stove'],
    heating: 'Gas',
    cooling: 'Central Air',
    flooring: ['Hardwood', 'Tile'],
    images: ['https://picsum.photos/seed/oakland-split-level/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Charming split-level home in Oakland within walking distance of University of Pittsburgh and Carnegie Mellon. Features updated bathrooms, original hardwood floors, and large corner lot. Great investment opportunity in a high-demand area.'
  },
  {
    id: 7,
    address: '456 Stanton Ave',
    city: 'Highland Park',
    state: 'Pennsylvania',
    zipCode: '15206',
    price: 425000,
    type: 'Residential',
    sqft: 1950,
    beds: 3,
    baths: 2,
    yearBuilt: 1940,
    propertyStyle: 'Craftsman',
    condition: 'Good',
    features: ['Original Woodwork', 'Fireplace', 'Large Windows', 'Near Park'],
    appliances: ['Dishwasher', 'Refrigerator'],
    heating: 'Gas',
    cooling: 'Window Units',
    flooring: ['Hardwood'],
    images: ['https://picsum.photos/seed/highland-park-craftsman/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Beautiful Craftsman home in Highland Park featuring original woodwork, built-ins, and fireplace. Large windows provide natural light throughout. Walking distance to Highland Park and close to major highways. Character-filled home with modern updates.'
  },
  {
    id: 8,
    address: '654 Liberty Ave',
    city: 'Strip District',
    state: 'Pennsylvania',
    zipCode: '15222',
    price: 395000,
    type: 'Residential',
    sqft: 1650,
    beds: 2,
    baths: 2,
    yearBuilt: 2005,
    propertyStyle: 'Loft',
    condition: 'Excellent',
    features: ['Exposed Brick', 'High Ceilings', 'Industrial Style', 'City Views'],
    appliances: ['Dishwasher', 'Refrigerator', 'Washer', 'Dryer'],
    heating: 'Heat Pump',
    cooling: 'Central Air',
    flooring: ['Concrete', 'Hardwood'],
    images: ['https://picsum.photos/seed/strip-district-loft/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Stylish loft conversion in the vibrant Strip District with exposed brick walls, high ceilings, and industrial elements. Features city views, modern appliances, and open concept living. Perfect for urban living near restaurants, shops, and nightlife.'
  },
  {
    id: 9,
    address: '987 Beechwood Blvd',
    city: 'Squirrel Hill',
    state: 'Pennsylvania',
    zipCode: '15217',
    price: 750000,
    type: 'Residential',
    sqft: 3500,
    beds: 4,
    baths: 3,
    halfBaths: 1,
    yearBuilt: 1995,
    propertyStyle: 'Traditional',
    condition: 'Excellent',
    features: ['Large Kitchen', 'Master Suite', 'Finished Basement', 'Two-Car Garage'],
    appliances: ['Dishwasher', 'Refrigerator', 'Washer', 'Dryer', 'Double Oven'],
    heating: 'Gas',
    cooling: 'Central Air',
    flooring: ['Hardwood', 'Tile', 'Carpet'],
    images: ['https://picsum.photos/seed/squirrel-hill-traditional/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Elegant traditional home in prestigious Squirrel Hill with large gourmet kitchen, master suite with walk-in closet, finished basement, and two-car garage. Prime location near Frick Park, schools, and shopping. Perfect for families seeking luxury and convenience.'
  },
  {
    id: 10,
    address: '147 Regent Square',
    city: 'Regent Square',
    state: 'Pennsylvania',
    zipCode: '15218',
    price: 325000,
    type: 'Residential',
    sqft: 1400,
    beds: 2,
    baths: 1,
    yearBuilt: 1920,
    propertyStyle: 'Bungalow',
    condition: 'Fair',
    features: ['Original Character', 'Front Porch', 'Hardwood Floors', 'Near Transit'],
    appliances: ['Dishwasher'],
    heating: 'Gas',
    cooling: 'None',
    flooring: ['Hardwood'],
    images: ['https://picsum.photos/seed/regent-square-bungalow/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Charming 1920s bungalow in Regent Square with original character details, front porch, and hardwood floors throughout. Near public transit and Frick Park. Great opportunity for first-time buyers or investors looking for a character home with potential.'
  }
];

// Fix: Add investor listings data
export const INVESTOR_LISTINGS: Listing[] = [
  // COMMERCIAL PROPERTIES (10)
  {
    id: 11,
    address: '101 Smithfield St',
    city: 'Downtown',
    state: 'Pennsylvania',
    zipCode: '15222',
    price: 2500000,
    type: 'Commercial',
    sqft: 10000,
    yearBuilt: 1985,
    propertyStyle: 'Office Building',
    condition: 'Good',
    parkingSpaces: 25,
    zoning: 'Commercial',
    features: ['Prime Location', 'Updated HVAC', 'Elevator', 'Street Level Retail'],
    heating: 'Central',
    cooling: 'Central',
    images: ['https://picsum.photos/seed/downtown-office-building/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Prime downtown office building with street-level retail space, updated HVAC system, elevator access, and 25 parking spaces. Excellent location for professional services or mixed-use development. Strong rental income potential.'
  },
  {
    id: 12,
    address: '202 Liberty Ave',
    city: 'Strip District',
    state: 'Pennsylvania',
    zipCode: '15222',
    price: 1200000,
    type: 'Commercial',
    sqft: 8000,
    yearBuilt: 1950,
    propertyStyle: 'Mixed Use Building',
    condition: 'Good',
    parkingSpaces: 15,
    zoning: 'Mixed Use',
    features: ['Street Level Retail', 'Office Space', 'Off-Street Parking', 'Near Strip District'],
    heating: 'Gas',
    cooling: 'Window Units',
    flooring: ['Hardwood', 'Tile'],
    rentalIncome: 12000,
    capRate: 8.5,
    images: ['https://picsum.photos/seed/strip-district-mixed-use/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Excellent mixed-use building in the Strip District with strong rental income of $12,000/month. Features street-level retail space, office space above, and off-street parking. High occupancy rate and excellent cap rate.'
  },
  {
    id: 13,
    address: '303 River Rd',
    city: 'South Side',
    state: 'Pennsylvania',
    zipCode: '15203',
    price: 3800000,
    type: 'Commercial',
    sqft: 25000,
    yearBuilt: 1990,
    propertyStyle: 'Warehouse',
    condition: 'Excellent',
    parkingSpaces: 50,
    zoning: 'Industrial',
    features: ['Loading Docks', 'High Ceilings', 'Office Space', 'Rail Access'],
    heating: 'Gas',
    cooling: 'None',
    flooring: ['Concrete'],
    images: ['https://picsum.photos/seed/south-side-warehouse/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Modern warehouse facility with loading docks, high ceilings, office space, and rail access. Perfect for distribution, manufacturing, or storage. Located in South Side with easy highway access and strong industrial market.'
  },
  {
    id: 14,
    address: '404 Innovation Dr',
    city: 'Oakland',
    state: 'Pennsylvania',
    zipCode: '15213',
    price: 1800000,
    type: 'Commercial',
    sqft: 12000,
    yearBuilt: 2015,
    propertyStyle: 'Mixed Use',
    condition: 'Excellent',
    parkingSpaces: 15,
    zoning: 'Mixed Use',
    features: ['Modern Design', 'Tech Ready', 'Near Universities', 'Retail Space'],
    heating: 'Heat Pump',
    cooling: 'Central',
    flooring: ['Concrete', 'Tile'],
    images: ['https://picsum.photos/seed/oakland-tech-building/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Modern mixed-use building in Oakland near Carnegie Mellon and University of Pittsburgh. Tech-ready office space with retail on the ground floor. Excellent location for tech companies or professional services.'
  },
  {
    id: 15,
    address: '555 Fifth Ave',
    city: 'Downtown',
    state: 'Pennsylvania',
    zipCode: '15222',
    price: 4200000,
    type: 'Commercial',
    sqft: 18000,
    yearBuilt: 2000,
    propertyStyle: 'Class A Office',
    condition: 'Excellent',
    parkingSpaces: 40,
    zoning: 'Commercial',
    features: ['LEED Certified', 'Concierge', 'Conference Center', 'City Views'],
    heating: 'Central',
    cooling: 'Central',
    flooring: ['Carpet', 'Tile'],
    rentalIncome: 25000,
    capRate: 6.2,
    images: ['https://picsum.photos/seed/downtown-class-a-office/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Premium Class A office building in the heart of downtown with LEED certification, full-service concierge, state-of-the-art conference center, and panoramic city views. Prime location with excellent tenant roster and strong rental income.'
  },
  {
    id: 16,
    address: '666 Butler St',
    city: 'Lawrenceville',
    state: 'Pennsylvania',
    zipCode: '15201',
    price: 850000,
    type: 'Commercial',
    sqft: 5000,
    yearBuilt: 1920,
    propertyStyle: 'Retail Building',
    condition: 'Good',
    parkingSpaces: 8,
    zoning: 'Commercial',
    features: ['Historic Building', 'Storefront', 'Upper Level Office', 'High Traffic'],
    heating: 'Gas',
    cooling: 'Window Units',
    flooring: ['Hardwood', 'Tile'],
    rentalIncome: 6500,
    capRate: 7.8,
    images: ['https://picsum.photos/seed/lawrenceville-retail-building/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Historic retail building on Butler Street in trendy Lawrenceville with original storefront, upper level office space, and high foot traffic. Perfect for boutique retail or restaurant. Strong rental income in growing neighborhood.'
  },
  {
    id: 17,
    address: '777 Carson St',
    city: 'South Side',
    state: 'Pennsylvania',
    zipCode: '15203',
    price: 1500000,
    type: 'Commercial',
    sqft: 7500,
    yearBuilt: 1980,
    propertyStyle: 'Medical Office',
    condition: 'Good',
    parkingSpaces: 20,
    zoning: 'Commercial',
    features: ['Medical Zoning', 'Parking Lot', 'Updated Interior', 'Near Hospital'],
    heating: 'Central',
    cooling: 'Central',
    flooring: ['Tile', 'Carpet'],
    rentalIncome: 9500,
    capRate: 7.2,
    images: ['https://picsum.photos/seed/south-side-medical-office/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Medical office building in South Side with medical zoning, dedicated parking lot, updated interior, and proximity to major hospital. Ideal for medical practices or healthcare services. Stable rental income with long-term tenants.'
  },
  {
    id: 18,
    address: '888 Forbes Ave',
    city: 'Oakland',
    state: 'Pennsylvania',
    zipCode: '15213',
    price: 2200000,
    type: 'Commercial',
    sqft: 15000,
    yearBuilt: 1975,
    propertyStyle: 'Research Building',
    condition: 'Good',
    parkingSpaces: 30,
    zoning: 'Commercial',
    features: ['Lab Space', 'Research Zoning', 'Near Universities', 'Loading Dock'],
    heating: 'Central',
    cooling: 'Central',
    flooring: ['Concrete', 'Tile'],
    rentalIncome: 18000,
    capRate: 7.8,
    images: ['https://picsum.photos/seed/oakland-research-building/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Specialized research building in Oakland with lab space, research zoning, and proximity to major universities. Features loading dock and specialized infrastructure. Perfect for biotech, research companies, or university partnerships.'
  },
  {
    id: 19,
    address: '999 Penn Ave',
    city: 'Strip District',
    state: 'Pennsylvania',
    zipCode: '15222',
    price: 950000,
    type: 'Commercial',
    sqft: 6000,
    yearBuilt: 1965,
    propertyStyle: 'Industrial Building',
    condition: 'Fair',
    parkingSpaces: 12,
    zoning: 'Industrial',
    features: ['High Ceilings', 'Loading Bay', 'Office Space', 'Storage Area'],
    heating: 'Gas',
    cooling: 'None',
    flooring: ['Concrete'],
    rentalIncome: 5500,
    capRate: 6.8,
    images: ['https://picsum.photos/seed/strip-district-industrial/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Industrial building in Strip District with high ceilings, loading bay, office space, and storage area. Perfect for manufacturing, warehousing, or light industrial use. Good rental income in established industrial area.'
  },
  {
    id: 20,
    address: '1110 Walnut St',
    city: 'Shadyside',
    state: 'Pennsylvania',
    zipCode: '15232',
    price: 1350000,
    type: 'Commercial',
    sqft: 8500,
    yearBuilt: 1990,
    propertyStyle: 'Professional Building',
    condition: 'Excellent',
    parkingSpaces: 25,
    zoning: 'Commercial',
    features: ['Modern Design', 'Professional Tenants', 'Conference Rooms', 'Elevator'],
    heating: 'Central',
    cooling: 'Central',
    flooring: ['Carpet', 'Tile'],
    rentalIncome: 11000,
    capRate: 8.1,
    images: ['https://picsum.photos/seed/shadyside-professional-building/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Modern professional building in Shadyside with contemporary design, professional tenant mix, conference facilities, and elevator access. Excellent location near shopping and restaurants. Strong rental income with quality tenants.'
  },

  // LAND PROPERTIES (10)
  {
    id: 21,
    address: '500 Development Way',
    city: 'East Liberty',
    state: 'Pennsylvania',
    zipCode: '15206',
    price: 750000,
    type: 'Land',
    sqft: 43560,
    lotSize: 43560,
    landUse: 'Residential Development',
    zoning: 'R-2',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer'],
    features: ['Corner Lot', 'Zoned for Multi-Family', 'Near Transit', 'Development Ready'],
    images: ['https://picsum.photos/seed/east-liberty-development-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Prime development land in East Liberty, zoned R-2 for multi-family residential development. One-acre corner lot with all utilities available. Perfect for townhome or apartment development. Near transit and growing neighborhood with strong appreciation potential.'
  },
  {
    id: 22,
    address: '600 Industrial Blvd',
    city: 'Hazelwood',
    state: 'Pennsylvania',
    zipCode: '15207',
    price: 1250000,
    type: 'Land',
    sqft: 87120,
    lotSize: 87120,
    landUse: 'Industrial Development',
    zoning: 'I-1',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer'],
    features: ['Rail Access', 'Highway Access', 'Flat Terrain', 'Zoned Industrial'],
    images: ['https://picsum.photos/seed/hazelwood-industrial-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Large industrial development site in Hazelwood with rail access, highway proximity, flat terrain, and I-1 industrial zoning. Perfect for manufacturing, distribution, or logistics facilities. All utilities available and ready for development.'
  },
  {
    id: 23,
    address: '700 Residential Rd',
    city: 'Brookline',
    state: 'Pennsylvania',
    zipCode: '15226',
    price: 450000,
    type: 'Land',
    sqft: 21780,
    lotSize: 21780,
    landUse: 'Residential Development',
    zoning: 'R-1',
    utilities: ['Electric', 'Water', 'Sewer'],
    features: ['Subdivision Potential', 'Mature Trees', 'Gentle Slope', 'Near Schools'],
    images: ['https://picsum.photos/seed/brookline-residential-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Residential development land in Brookline with subdivision potential, mature trees, gentle slope, and proximity to schools. Zoned R-1 for single-family homes. Perfect for small subdivision or custom home development.'
  },
  {
    id: 24,
    address: '800 Commercial Ave',
    city: 'Robinson Township',
    state: 'Pennsylvania',
    zipCode: '15205',
    price: 1850000,
    type: 'Land',
    sqft: 130680,
    lotSize: 130680,
    landUse: 'Commercial Development',
    zoning: 'C-1',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer', 'Cable'],
    features: ['Highway Frontage', 'Traffic Count', 'Retail Zoning', 'Anchor Tenant Potential'],
    images: ['https://picsum.photos/seed/robinson-commercial-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Premium commercial development site in Robinson Township with highway frontage, high traffic count, retail zoning, and anchor tenant potential. Perfect for shopping center, retail plaza, or mixed-use development. All utilities available.'
  },
  {
    id: 25,
    address: '900 Farm Rd',
    city: 'Cranberry Township',
    state: 'Pennsylvania',
    zipCode: '16066',
    price: 950000,
    type: 'Land',
    sqft: 65340,
    lotSize: 65340,
    landUse: 'Agricultural',
    zoning: 'Agricultural',
    utilities: ['Electric', 'Water'],
    features: ['Farmland', 'Barn', 'Pond', 'Development Potential'],
    images: ['https://picsum.photos/seed/cranberry-agricultural-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Agricultural land in Cranberry Township with existing farmland, barn, pond, and future development potential. Currently used for farming but could be converted to residential development. Great investment opportunity in growing area.'
  },
  {
    id: 26,
    address: '1000 Waterfront Dr',
    city: 'North Shore',
    state: 'Pennsylvania',
    zipCode: '15212',
    price: 3200000,
    type: 'Land',
    sqft: 26136,
    lotSize: 26136,
    landUse: 'Mixed Use Development',
    zoning: 'Mixed Use',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer'],
    features: ['Waterfront', 'City Views', 'Mixed Use Zoning', 'Premium Location'],
    images: ['https://picsum.photos/seed/north-shore-waterfront-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Premium waterfront development site on North Shore with city views, mixed-use zoning, and premium location. Perfect for luxury condos, hotel, or mixed-use development. Rare waterfront opportunity with all utilities available.'
  },
  {
    id: 27,
    address: '1100 Suburban Blvd',
    city: 'Monroeville',
    state: 'Pennsylvania',
    zipCode: '15146',
    price: 675000,
    type: 'Land',
    sqft: 32670,
    lotSize: 32670,
    landUse: 'Office Development',
    zoning: 'Office',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer'],
    features: ['Office Zoning', 'Highway Access', 'Professional Area', 'Parking Potential'],
    images: ['https://picsum.photos/seed/monroeville-office-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Office development land in Monroeville with office zoning, highway access, professional area location, and parking potential. Perfect for corporate office building, medical office, or professional services. All utilities available.'
  },
  {
    id: 28,
    address: '1200 Tech Park Dr',
    city: 'Homestead',
    state: 'Pennsylvania',
    zipCode: '15120',
    price: 1450000,
    type: 'Land',
    sqft: 43560,
    lotSize: 43560,
    landUse: 'Technology Development',
    zoning: 'Technology',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer', 'Fiber'],
    features: ['Tech Zoning', 'Fiber Internet', 'Near Universities', 'Innovation District'],
    images: ['https://picsum.photos/seed/homestead-tech-park-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Technology development site in Homestead with tech zoning, fiber internet, proximity to universities, and innovation district location. Perfect for tech campus, research facility, or startup incubator. All utilities including fiber available.'
  },
  {
    id: 29,
    address: '1300 Greenfield Ave',
    city: 'Greenfield',
    state: 'Pennsylvania',
    zipCode: '15217',
    price: 380000,
    type: 'Land',
    sqft: 10890,
    lotSize: 10890,
    landUse: 'Residential Development',
    zoning: 'R-2',
    utilities: ['Electric', 'Water', 'Sewer'],
    features: ['Duplex Potential', 'City Views', 'Near Park', 'Transit Access'],
    images: ['https://picsum.photos/seed/greenfield-residential-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Residential development land in Greenfield with duplex potential, city views, proximity to park, and transit access. Zoned R-2 for multi-family development. Perfect for duplex or small multi-unit development.'
  },
  {
    id: 30,
    address: '1400 Airport Blvd',
    city: 'Moon Township',
    state: 'Pennsylvania',
    zipCode: '15108',
    price: 2200000,
    type: 'Land',
    sqft: 174240,
    lotSize: 174240,
    landUse: 'Industrial Development',
    zoning: 'Industrial',
    utilities: ['Electric', 'Gas', 'Water', 'Sewer'],
    features: ['Airport Proximity', 'Rail Access', 'Industrial Zoning', 'Logistics Hub'],
    images: ['https://picsum.photos/seed/moon-airport-industrial-land/800/600'],
    videos: [],
    listingDate: new Date().toISOString().split('T')[0],
    lastUpdated: new Date().toISOString().split('T')[0],
    status: 'Active',
    aiPrompt: 'Large industrial development site near Pittsburgh International Airport with rail access, industrial zoning, and logistics hub potential. Perfect for distribution center, manufacturing, or logistics facility. All utilities available.'
  }
];

// Fix: Define and export SVG icons used in various components
export const BedIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
    </svg>
);

export const BathIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 1.5m1-1.5V5.25m0 0l-1-1.5m1 1.5h.008v.008H12V5.25z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 21a2.25 2.25 0 002.25-2.25V16.5h12v2.25c0 1.24 1.01 2.25 2.25 2.25s2.25-1.01 2.25-2.25V16.5h-16.5v2.25A2.25 2.25 0 003.75 21z" />
    </svg>
);

export const SqftIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 8.25v10.5a2.25 2.25 0 01-2.25-2.25H5.25a2.25 2.25 0 01-2.25-2.25V8.25m18 0V5.25a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 5.25v3M3 18.75V16.5m18-8.25V16.5" />
    </svg>
);

export const UnitsIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h6M9 11.25h6m-6 4.5h6M6.75 6.75h.008v.008H6.75V6.75zm.008 4.5h-.008v.008h.008v-.008zm0 4.5h-.008v.008h.008v-.008zm-2.25-4.5h.008v.008H4.5v-.008zm0 4.5h.008v.008H4.5v-.008zm12-4.5h.008v.008h-.008v-.008zm0 4.5h.008v.008h-.008v-.008z" />
    </svg>
);

export const TwitterIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.223.085a4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
    </svg>
);

export const FacebookIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M22.675 0h-21.35C.59 0 0 .59 0 1.325v21.35C0 23.41.59 24 1.325 24H12.82v-9.29H9.692v-3.622h3.128V8.413c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12V24h5.694c.735 0 1.325-.59 1.325-1.325V1.325C24 .59 23.41 0 22.675 0z" />
    </svg>
);

export const InstagramIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M12 2.163c3.204 0 3.584.012 4.85.07 1.272.058 2.122.218 2.88.482.748.27 1.33.64 1.912 1.225.583.583.955 1.164 1.226 1.912.264.758.424 1.608.482 2.88.058 1.266.07 1.646.07 4.85s-.012 3.584-.07 4.85c-.058 1.272-.218 2.122-.482 2.88-.27.748-.64 1.33-1.225 1.912-.583.583-1.164.955-1.912 1.226-.758.264-1.608.424-2.88.482-1.266.058-1.646.07-4.85.07s-3.584-.012-4.85-.07c-1.272-.058-2.122-.218-2.88-.482-.748-.27-1.33-.64-1.912-1.225-.583.583-.955-1.164-1.226-1.912-.264-.758-.424-1.608-.482-2.88-.058-1.266-.07-1.646-.07-4.85s.012-3.584.07-4.85c.058-1.272.218 2.122.482-2.88.27.748.64 1.33 1.225 1.912.583.583 1.164.955 1.912 1.226.758.264 1.608.424 2.88.482C8.416 2.175 8.796 2.163 12 2.163zm0-2.163C8.734 0 8.344.012 7.078.07c-1.356.06-2.3.22-3.132.52-1.12.39-1.98.9-2.848 1.768S.59 4.61.2 5.73C-.1 6.56-.26 7.508-.32 8.864-.38 10.13-.392 10.52-.392 12s.013 1.87.07 3.136c.06 1.356.22 2.3.52 3.132.39 1.12.9 1.98 1.768 2.848.868.868 1.728 1.378 2.848 1.768.832.3 1.776.46 3.132.52 1.266.058 1.656.07 4.922.07s3.656-.012 4.922-.07c1.356-.06 2.3-.22 3.132-.52 1.12-.39 1.98-.9 2.848-1.768.868-.868 1.378-1.728 1.768-2.848.3-.832.46-1.776.52-3.132.058-1.266.07-1.656.07-4.922s-.012-3.656-.07-4.922c-.06-1.356-.22-2.3-.52-3.132-.39-1.12-.9-1.98-1.768-2.848C20.9 1.47 20.04.96 18.92.59c-.832-.3-1.776-.46-3.132-.52C14.524.01 14.134 0 12 0zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zM12 16a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.88 1.44 1.44 0 000-2.88z" />
    </svg>
);

// Additional icons for property stats
export const GarageIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M4 6h16v2H4V6zm0 5h16v9H4v-9zm2 2v5h12v-5H6zm2 2h8v1H8v-1z"/>
    </svg>
);

export const YearIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6l5.25 3.15-.75 1.23L11 13V7z"/>
    </svg>
);

export const MLSIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
    </svg>
);

export const LotSizeIcon = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
        <path d="M3 3v18h18V3H3zm16 16H5V5h14v14zm-8-12h2v2h-2V7zm0 4h2v2h-2v-2zm0 4h2v2h-2v-2zm4-8h2v2h-2V7zm0 4h2v2h-2v-2zm0 4h2v2h-2v-2z"/>
    </svg>
);